# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./  # Le dossier de déploiement

jobs:
  build-project:
    name: Build and Deploy neolean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Apache and PHP
        run: |
          sudo apt-get update
          sudo apt-get install apache2 php libapache2-mod-php

      # Ici, vous pourriez ajouter d'autres étapes pour installer les dépendances de votre projet PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Replace with the PHP version you want to use

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
      - name: Configure Apache for PHP
        run: |
          sudo cp /etc/apache2/mods-available/php7.4.load /etc/apache2/mods-enabled/
          sudo service apache2 restart

      - name: Deploy with Deploy Now
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 816fb7ef-fcbe-4dd6-9e35-27e1ce9378ce
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/neolean/config.yaml
          action: upload
